// Generated by CoffeeScript 1.10.0
(function() {
  var _randomNum, readTextFile;

  _randomNum = function(max, min) {
    if (min == null) {
      min = 0;
    }
    return Math.floor(Math.random() * (max - min) + min);
  };

  readTextFile = function(file) {
    var rawFile;
    rawFile = new XMLHttpRequest();
    rawFile.open("GET", file, false);
    rawFile.onreadystatechange = function() {
      var allText, line;
      if (rawFile.readyState === 4) {
        if (rawFile.status === 200 || rawFile.status === 0) {
          allText = rawFile.responseText;
          line = allText.split("\n")[_randomNum(1, 568)];
          document.getElementById("num").innerHTML = line.split(",")[0];
          document.getElementById("section").innerHTML = line.split(",")[1];
          return document.getElementById("container").innerHTML = line.split(",")[2];
        }
      }
    };
    return rawFile.send(null);
  };

  $(function() {
    readTextFile("./obliquestrategies.csv");
    return $(".s12").click(function() {
      return readTextFile("./obliquestrategies.csv");
    });
  });

}).call(this);
